//! Shared types for Belisarius. Pure data — no I/O lives here.
//!
//! When the `ts` cargo feature is enabled, each `#[derive(TS)]` struct/enum
//! emits a `.ts` file under `web/src/types/generated/` via a `#[test]` block
//! generated by `ts-rs`. Run `cargo test -p belisarius-core --features ts` to
//! refresh the bindings; the runtime build (no feature) is unchanged.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use time::OffsetDateTime;

#[cfg(feature = "ts")]
use ts_rs::TS;

pub type Json = serde_json::Value;

/// Top-level scan output. v1 is intentionally thin: file inventory + import edges.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub struct Scan {
    pub root: String,
    #[serde(with = "time::serde::iso8601")]
    #[cfg_attr(feature = "ts", ts(type = "string"))]
    pub scanned_at: OffsetDateTime,
    pub files: Vec<FileNode>,
    pub edges: Vec<ImportEdge>,
    pub language_summary: BTreeMap<String, LanguageSummary>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub struct FileNode {
    /// Path relative to scan root, forward-slash separated.
    pub path: String,
    pub language: String,
    pub loc: u32,
    pub bytes: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub struct ImportEdge {
    pub from: String,
    /// Raw module specifier (e.g., "./foo", "crate::bar", "os.path"). Resolution happens later.
    pub to: String,
    pub kind: EdgeKind,
    /// 1-indexed line in `from` where this import appears. 0 means unknown.
    #[serde(default)]
    pub line: u32,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub enum EdgeKind {
    Import,
    Use,
    From,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub struct LanguageSummary {
    pub files: u32,
    pub loc: u32,
    pub bytes: u64,
}

/// Resolved file-graph: every edge connects two file paths in the scan.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub struct Graph {
    pub root: String,
    pub nodes: Vec<GraphNode>,
    pub edges: Vec<GraphEdge>,
    /// Edges whose target could not be resolved to a file in the scan
    /// (external packages, std-lib, etc.).
    pub unresolved: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub struct GraphNode {
    pub id: String,
    pub language: String,
    pub loc: u32,
    pub in_degree: u32,
    pub out_degree: u32,
    pub is_entry_point: bool,
    #[serde(default)]
    pub depth_from_entry: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub struct GraphEdge {
    pub from: String,
    pub to: String,
    /// 1-indexed line in `from` where the import lives. 0 means unknown.
    #[serde(default)]
    pub line: u32,
}

/// Per-function AST-extracted info with complexity metrics.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub struct FunctionInfo {
    pub file: String,
    pub name: String,
    pub start_line: u32,
    pub end_line: u32,
    pub loc: u32,
    pub params: u32,
    pub cyclomatic: u32,
    pub cognitive: u32,
    /// First 16 hex chars of blake3(body_text) — for duplicate detection later.
    pub body_hash: String,
}

/// File-level rollup of function metrics.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub struct FileMetrics {
    pub path: String,
    pub function_count: u32,
    pub max_cyclomatic: u32,
    pub total_cyclomatic: u32,
    pub max_cognitive: u32,
    pub longest_function_loc: u32,
    pub avg_cyclomatic: f32,
}

/// A strongly-connected component (size > 1) or self-loop in the file graph.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub struct GraphCycle {
    pub nodes: Vec<String>,
    pub size: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub struct QualityAxes {
    pub complexity: Option<f32>,
    pub acyclicity: Option<f32>,
    pub dead_code: Option<f32>,
    pub coupling: Option<f32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub enum QualityIssue {
    HotFunction {
        file: String,
        name: String,
        start_line: u32,
        cyclomatic: u32,
        cognitive: u32,
    },
    Cycle {
        nodes: Vec<String>,
    },
    DeadFile {
        path: String,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub struct Quality {
    pub score: Option<f32>,
    pub axes: QualityAxes,
    pub top_issues: Vec<QualityIssue>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub struct AnalysisReport {
    pub scan: Scan,
    pub graph: Graph,
    pub functions: Vec<FunctionInfo>,
    pub file_metrics: Vec<FileMetrics>,
    pub cycles: Vec<GraphCycle>,
    pub max_depth: u32,
    pub quality: Quality,
}

/// One issue surfaced by an external code-quality tool.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub struct Diagnostic {
    /// Tool that produced this diagnostic — `"clippy"`, `"semgrep"`, etc.
    pub tool: String,
    pub rule_id: String,
    pub severity: Severity,
    pub file: String,
    pub start_line: u32,
    pub end_line: u32,
    #[serde(default)]
    pub start_col: u32,
    #[serde(default)]
    pub end_col: u32,
    pub message: String,
    #[serde(default)]
    pub help: Option<String>,
    #[serde(default)]
    pub url: Option<String>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "lowercase")]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub enum Severity {
    Error,
    Warning,
    Info,
    Hint,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub struct ToolStatus {
    pub name: String,
    pub installed: bool,
    /// True when the tool was deemed applicable to the project (e.g. clippy
    /// to a Cargo project, eslint to a package.json'd dir).
    pub applied: bool,
    /// Wall-clock time the tool spent during the last run.
    #[serde(default)]
    pub elapsed_ms: u64,
    /// Diagnostics produced in the last run.
    #[serde(default)]
    pub count: u32,
    /// Captured error message if the tool failed to run.
    #[serde(default)]
    pub error: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub struct DiagnosticsReport {
    pub tools_ran: Vec<ToolStatus>,
    pub diagnostics: Vec<Diagnostic>,
    pub counts_by_tool: BTreeMap<String, u32>,
    pub counts_by_severity: BTreeMap<String, u32>,
}

/// One public item the codebase exposes — a function, type, module, HTTP
/// route, CLI subcommand, etc. The aggregate inventory is the answer to
/// "what does this codebase do?"
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub struct SurfaceItem {
    pub file: String,
    pub language: String,
    pub kind: SurfaceKind,
    pub name: String,
    #[serde(default)]
    pub signature: Option<String>,
    pub line: u32,
    /// HTTP method when `kind == HttpRoute`.
    #[serde(default)]
    pub method: Option<String>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "snake_case")]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub enum SurfaceKind {
    Function,
    Type, // struct / enum / class / trait / interface / type alias
    Module,
    Constant,
    ReExport,
    HttpRoute,
    CliCommand,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
#[cfg_attr(feature = "ts", ts(export, export_to = "web/src/types/generated/"))]
pub struct SurfaceReport {
    pub items: Vec<SurfaceItem>,
    pub counts_by_kind: BTreeMap<String, u32>,
    pub counts_by_language: BTreeMap<String, u32>,
}
