// Wire types shared with the Rust backend are generated by `ts-rs` from
// `crates/belisarius-core/src/lib.rs`. Re-run `cargo test -p belisarius-core
// --features ts` after editing those structs; the output lands in
// `web/src/types/generated/` (checked in).
//
// Shapes below that are NOT generated are server-side composites (response
// wrappers like `Brief`, `FunctionDetail`, `QualitySummary`) — these will
// migrate to `ts-rs` next as their service modules are annotated.
import type {
  AnalysisReport,
  Brief,
  CallersResponse,
  Diagnostic,
  DiagnosticsReport,
  EdgeKind,
  FileMetrics,
  FileNode,
  FlowReport,
  FunctionDetail,
  FunctionInfo,
  FunctionsResponse,
  Graph,
  GraphCycle,
  GraphEdge,
  GraphNode,
  ImpactReport,
  ImportEdge,
  LanguageSummary,
  MarkerHit,
  MarkersResponse,
  Quality,
  QualityAxes,
  QualityIssue,
  QualityResponse,
  Range,
  RefsResponse,
  Scan,
  Severity,
  SnippetResponse,
  SurfaceItem,
  SurfaceKind,
  SurfaceReport,
  Symbol360,
  SymbolMatch,
  SymbolOccurrence,
  SymbolsSearchResponse,
  SymbolsStatusResponse,
  ToolStatus,
} from "./types/generated";

export type {
  AnalysisReport,
  Brief,
  CallersResponse,
  Diagnostic,
  DiagnosticsReport,
  EdgeKind,
  FileMetrics,
  FileNode,
  FlowReport,
  FunctionDetail,
  FunctionInfo,
  FunctionsResponse,
  Graph,
  GraphCycle,
  GraphEdge,
  GraphNode,
  ImpactReport,
  ImportEdge,
  LanguageSummary,
  MarkerHit,
  MarkersResponse,
  Quality,
  QualityAxes,
  QualityIssue,
  QualityResponse,
  Range,
  RefsResponse,
  Scan,
  Severity,
  SnippetResponse,
  SurfaceItem,
  SurfaceKind,
  SurfaceReport,
  Symbol360,
  SymbolMatch,
  SymbolOccurrence,
  SymbolsSearchResponse,
  SymbolsStatusResponse,
  ToolStatus,
};

// Back-compat aliases — older callers still reference these names.
//   QualitySummary  ← QualityResponse
//   Snippet         ← SnippetResponse (the project endpoint; the generated
//                     `Snippet` is the smaller function_detail-nested type)
//   SymbolStatus    ← SymbolsStatusResponse
//   SymbolRef       ← SymbolOccurrence (refs/call_sites array elements)
export type QualitySummary = QualityResponse;
export type Snippet = SnippetResponse;
export type SymbolStatus = SymbolsStatusResponse;
export type SymbolRef = SymbolOccurrence;

export type FileDsm = {
  file: string;
  language: string;
  loc: number;
  in_degree: number;
  out_degree: number;
  outbound: Array<{ to: string; line: number; in_function?: string | null }>;
  inbound: Array<{ from: string; line: number; in_function?: string | null }>;
  externals: Array<{ spec: string; line: number; kind: string; in_function?: string | null }>;
  functions: Array<{
    name: string;
    start_line: number;
    end_line: number;
    loc: number;
    params: number;
    cyclomatic: number;
    cognitive: number;
  }>;
};

// Brief / FunctionDetail re-exported from `./types/generated`.

// SymbolStatus / SymbolMatch / SymbolRef / RefsResponse / CallerEntry /
// CallersResponse re-exported from `./types/generated` (with back-compat
// aliases at the top of this file for the renamed ones).
//
// `CallerEntry` is intentionally NOT re-exported here because its
// generated form is the `function_detail`-nested type with `Vec<CallSite>`,
// while the SCIP `/api/symbols/callers` endpoint uses
// `CallersResponse.callers[].call_sites: Vec<SymbolOccurrence>`. Consumers
// should reach into `CallersResponse` directly rather than spelling
// `CallerEntry`.

// QualitySummary / FunctionsResponse / Snippet / MarkerHit / MarkersResponse
// re-exported from `./types/generated` at the top of this file.

// Diagnostic / DiagnosticsReport re-exported from `./types/generated`.
//
// `DiagToolStatus` (below) is a thin variant returned by `GET
// /api/diagnostics/status` — it adds a `binary` field that the core
// `ToolStatus` type doesn't carry. Kept hand-rolled until the diagnostics
// HTTP handler is migrated to a service module that ts-rs can annotate.
export type DiagToolStatus = {
  name: string;
  binary?: string | null;
  installed: boolean;
  applied: boolean;
  elapsed_ms?: number;
  count?: number;
  error?: string | null;
};

export type DirectorySummary = {
  path: string;
  files: number;
  loc: number;
  in_edges: number;
  out_edges: number;
  cross_edges: number;
};

export type ArchitectureMermaid = {
  mermaid: string;
  view: 'module' | 'file';
  directory_summary: DirectorySummary[];
  nodes_total: number;
  edges_total: number;
  rendered_cap: number;
  group_depth: number;
};

export type GraphVizNode = {
  id: string;
  label: string;
  sublabel: string;
  language: string;
  file_count: number;
  loc: number;
  is_entry: boolean;
};

export type GraphVizEdge = {
  source: string;
  target: string;
  weight: number;
};

export type ArchitectureGraph = {
  view: 'module' | 'file';
  group_depth: number;
  nodes: GraphVizNode[];
  edges: GraphVizEdge[];
  nodes_total: number;
  edges_total: number;
  rendered_cap: number;
  directory_summary: DirectorySummary[];
};

export type ComponentProp = {
  name: string;
  type: string;
  required: boolean;
  description: string;
  default: string | null;
};

export type ComponentDoc = {
  file: string;
  name: string;
  description: string;
  props: ComponentProp[];
};

export type ComponentsResponse = {
  components: ComponentDoc[];
  count: number;
};

export type ArchitectureModule = {
  module: string;
  group_depth: number;
  file_count: number;
  total_loc: number;
  files: Array<{ path: string; language: string; loc: number }>;
  outgoing: Array<{ path: string; weight: number }>;
  incoming: Array<{ path: string; weight: number }>;
};

export type Hotspot = {
  path: string;
  churn: number;
  total_commits: number;
  complexity: number;
  function_count: number;
  score: number;
  last_edited: string | null;
  /** Author of the most recent commit that touched this file. */
  last_author: string | null;
  /** Most-prolific contributor inside the configured window. */
  top_author: string | null;
  /** Owners from `.github/CODEOWNERS` matching this path, or [] when no rule matches. */
  owners: string[];
};

export type TestGap = {
  source: string;
  language: string;
  loc: number;
  function_count: number;
  total_cyclomatic: number;
  max_cyclomatic: number;
};

export type TestMapping = {
  source: string;
  tests: string[];
};

export type TestMapSummary = {
  source_files: number;
  test_files: number;
  covered_files: number;
  gap_files: number;
  coverage_pct: number;
};

export type TestMap = {
  mappings: TestMapping[];
  gaps: TestGap[];
  summary: TestMapSummary;
};

export type NamedCommand = {
  name: string;
  command: string;
  source: string;
  purpose: string;
};

export type SuggestedCommands = {
  run: string | null;
  build: string | null;
  test: string | null;
  lint: string | null;
  format: string | null;
};

export type WorkspaceCommands = {
  package_scripts: NamedCommand[];
  cargo: NamedCommand[];
  just: NamedCommand[];
  make: NamedCommand[];
  python: NamedCommand[];
  workflows: NamedCommand[];
  suggested: SuggestedCommands;
};

// ─── Fleet ─────────────────────────────────────────────────────────────────

export type FleetAppSummary = {
  file_count: number;
  loc: number;
  primary_language: string | null;
  languages?: Record<string, { files: number; loc: number; bytes: number }>;
};

export type FleetApp = {
  name: string;
  path: string;
  description?: string | null;
  tags: string[];
  last_synced?: string | null;
  summary?: FleetAppSummary | null;
};

export type FleetListResponse = {
  apps: FleetApp[];
  config_path: string;
};

export type FleetSurfaceRow = {
  app: string;
  file: string;
  language: string;
  kind: string;
  name: string;
  signature: string | null;
  line: number;
  method: string | null;
};

export type FleetFindResponse = {
  count: number;
  results: FleetSurfaceRow[];
};

export type FleetHotspotRow = {
  app: string;
  file: string;
  churn: number;
  complexity: number;
  score: number;
  last_author: string | null;
  owners: string[];
};

export type FleetHotspotsResponse = {
  count: number;
  hotspots: FleetHotspotRow[];
};

export type FleetTestGapRow = {
  app: string;
  file: string;
  language: string;
  loc: number;
  function_count: number;
  total_cyclomatic: number;
};

export type FleetTestGapsResponse = {
  count: number;
  gaps: FleetTestGapRow[];
};

export type FleetDiffEntry = {
  kind: string;
  name: string;
  method: string | null;
  file: string;
  line: number;
};

export type FleetDiffResponse = {
  only_in_a: FleetDiffEntry[];
  only_in_b: FleetDiffEntry[];
  common_count: number;
};

export type HotspotsResponse = {
  repo_present: boolean;
  days_window: number;
  hotspots: Hotspot[];
  git_files_total: number;
};

// SurfaceKind / SurfaceItem / SurfaceReport re-exported from `./types/generated`.

// ─── Search / xref / context ───────────────────────────────────────────────

export type SearchHit = {
  chunk_id: number;
  file: string;
  lang: string;
  kind: 'function' | 'window' | 'artifact';
  name: string;
  start_line: number;
  end_line: number;
  snippet: string;
  score: number;
  bm25_rank: number | null;
  dense_rank: number | null;
};

export type SearchResponse = { hits: SearchHit[]; count: number };

export type IndexStatus = {
  state: 'idle' | 'indexing' | 'error';
  processed: number;
  total: number;
  chunk_count: number;
  model: string;
  started_at: number | null;
  finished_at: number | null;
  last_error: string | null;
  bm25_only: boolean;
};

// ImpactNode / ImpactReport / FlowNode / FlowReport / Symbol360 / Range /
// DefSite / CallerLite / CalleeLite re-exported from `./types/generated`.

export type ContextArtifact = {
  name: string;
  description: string;
  paths: string[];
  when?: string | null;
};

export type ContextListResponse = { artifacts: ContextArtifact[]; count: number };

export type ContextResolvedFile = { path: string; content: string };

export type ContextArtifactContent = {
  artifact: ContextArtifact;
  files: ContextResolvedFile[];
};

async function call<T>(
  path: string,
  init?: RequestInit,
  signal?: AbortSignal,
): Promise<T> {
  const resp = await fetch(path, {
    ...init,
    signal: signal ?? init?.signal,
    headers: { 'content-type': 'application/json', ...(init?.headers ?? {}) },
  });
  if (!resp.ok) {
    let detail = await resp.text();
    try {
      const j = JSON.parse(detail);
      if (j?.error) detail = j.error;
    } catch {
      /* ignore */
    }
    throw new Error(`HTTP ${resp.status}: ${detail}`);
  }
  return (await resp.json()) as T;
}

// Every method in `api` accepts an optional trailing `signal?: AbortSignal`.
// When passed (always passed from `queries.ts` via react-query's
// `QueryFunctionContext`), it propagates to `fetch` so unmounting a
// component or rapid path changes abort the in-flight request at the
// network layer — not just at the framework layer.
export const api = {
  scan: (path?: string, signal?: AbortSignal) =>
    call<Scan>(
      `/api/scan${path ? `?path=${encodeURIComponent(path)}` : ''}`,
      { method: 'POST' },
      signal,
    ),
  graph: (path?: string, signal?: AbortSignal) =>
    call<Graph>(
      `/api/graph${path ? `?path=${encodeURIComponent(path)}` : ''}`,
      { method: 'POST' },
      signal,
    ),
  symbolsStatus: (path: string, signal?: AbortSignal) =>
    call<SymbolStatus>(
      `/api/symbols/status?path=${encodeURIComponent(path)}`,
      undefined,
      signal,
    ),
  symbolsSearch: (path: string, q: string, limit = 30, signal?: AbortSignal) =>
    call<{ matches: SymbolMatch[] }>(
      `/api/symbols/search?path=${encodeURIComponent(path)}&q=${encodeURIComponent(q)}&limit=${limit}`,
      undefined,
      signal,
    ).then((r) => r.matches),
  symbolsRefs: (path: string, sym: string, signal?: AbortSignal) =>
    call<RefsResponse>(
      `/api/symbols/refs?path=${encodeURIComponent(path)}&sym=${encodeURIComponent(sym)}`,
      undefined,
      signal,
    ),
  symbolsCallers: (path: string, sym: string, signal?: AbortSignal) =>
    call<CallersResponse>(
      `/api/symbols/callers?path=${encodeURIComponent(path)}&sym=${encodeURIComponent(sym)}`,
      undefined,
      signal,
    ),
  quality: (path: string, signal?: AbortSignal) =>
    call<QualitySummary>(
      `/api/quality?path=${encodeURIComponent(path)}`,
      undefined,
      signal,
    ),
  brief: (path: string, signal?: AbortSignal) =>
    call<Brief>(`/api/brief?path=${encodeURIComponent(path)}`, undefined, signal),
  functionDetail: (path: string, file: string, name: string, signal?: AbortSignal) =>
    call<FunctionDetail>(
      `/api/function?path=${encodeURIComponent(path)}&file=${encodeURIComponent(file)}&name=${encodeURIComponent(name)}`,
      undefined,
      signal,
    ),
  functions: (
    path: string,
    opts: { minCc?: number; limit?: number; sortBy?: string; file?: string } = {},
    signal?: AbortSignal,
  ) => {
    const parts = [`path=${encodeURIComponent(path)}`];
    if (opts.minCc !== undefined) parts.push(`min_cc=${opts.minCc}`);
    if (opts.limit !== undefined) parts.push(`limit=${opts.limit}`);
    if (opts.sortBy) parts.push(`sort_by=${encodeURIComponent(opts.sortBy)}`);
    if (opts.file) parts.push(`file=${encodeURIComponent(opts.file)}`);
    return call<FunctionsResponse>(`/api/functions?${parts.join('&')}`, undefined, signal);
  },
  snippet: (path: string, file: string, line: number, radius = 25, signal?: AbortSignal) =>
    call<Snippet>(
      `/api/snippet?path=${encodeURIComponent(path)}&file=${encodeURIComponent(file)}&line=${line}&radius=${radius}`,
      undefined,
      signal,
    ),
  markers: (path: string, limit = 500, signal?: AbortSignal) =>
    call<MarkersResponse>(
      `/api/markers?path=${encodeURIComponent(path)}&limit=${limit}`,
      undefined,
      signal,
    ),
  fileDsm: (path: string, file: string, signal?: AbortSignal) =>
    call<FileDsm>(
      `/api/file_dsm?path=${encodeURIComponent(path)}&file=${encodeURIComponent(file)}`,
      undefined,
      signal,
    ),
  diagnosticsStatus: (path: string, signal?: AbortSignal) =>
    call<{ tools: DiagToolStatus[] }>(
      `/api/diagnostics/status?path=${encodeURIComponent(path)}`,
      undefined,
      signal,
    ),
  diagnosticsRun: (path: string, tools?: string[], force = false, signal?: AbortSignal) =>
    call<{ cached: boolean; report: DiagnosticsReport }>(
      '/api/diagnostics/run',
      {
        method: 'POST',
        body: JSON.stringify({ path, tools, force }),
      },
      signal,
    ),
  diagnosticsList: (
    path: string,
    opts: { tool?: string; severity?: string; file?: string; limit?: number } = {},
    signal?: AbortSignal,
  ) => {
    const parts = [`path=${encodeURIComponent(path)}`];
    if (opts.tool) parts.push(`tool=${encodeURIComponent(opts.tool)}`);
    if (opts.severity) parts.push(`severity=${encodeURIComponent(opts.severity)}`);
    if (opts.file) parts.push(`file=${encodeURIComponent(opts.file)}`);
    if (opts.limit) parts.push(`limit=${opts.limit}`);
    return call<{
      total_cached: number;
      returned: number;
      diagnostics: Diagnostic[];
      counts_by_tool: Record<string, number>;
      counts_by_severity: Record<string, number>;
      tools_ran: ToolStatus[];
    }>(`/api/diagnostics?${parts.join('&')}`, undefined, signal);
  },
  architectureMermaid: (
    path: string,
    opts: { view?: 'module' | 'file'; maxNodes?: number; groupDepth?: number } = {},
    signal?: AbortSignal,
  ) => {
    const parts = [`path=${encodeURIComponent(path)}`];
    parts.push(`view=${opts.view ?? 'module'}`);
    parts.push(`max_nodes=${opts.maxNodes ?? 60}`);
    parts.push(`group_depth=${opts.groupDepth ?? 2}`);
    return call<ArchitectureMermaid>(
      `/api/architecture/mermaid?${parts.join('&')}`,
      undefined,
      signal,
    );
  },
  architectureGraph: (
    path: string,
    opts: { view?: 'module' | 'file'; maxNodes?: number; groupDepth?: number } = {},
    signal?: AbortSignal,
  ) => {
    const parts = [`path=${encodeURIComponent(path)}`];
    parts.push(`view=${opts.view ?? 'module'}`);
    parts.push(`max_nodes=${opts.maxNodes ?? 60}`);
    parts.push(`group_depth=${opts.groupDepth ?? 2}`);
    return call<ArchitectureGraph>(
      `/api/architecture/graph?${parts.join('&')}`,
      undefined,
      signal,
    );
  },
  components: (path: string, signal?: AbortSignal) =>
    call<ComponentsResponse>(
      `/api/components?path=${encodeURIComponent(path)}`,
      undefined,
      signal,
    ),
  architectureModule: (path: string, module: string, groupDepth = 2, signal?: AbortSignal) =>
    call<ArchitectureModule>(
      `/api/architecture/module?path=${encodeURIComponent(path)}&module=${encodeURIComponent(module)}&group_depth=${groupDepth}`,
      undefined,
      signal,
    ),
  hotspots: (path: string, days = 90, limit = 40, signal?: AbortSignal) =>
    call<HotspotsResponse>(
      `/api/hotspots?path=${encodeURIComponent(path)}&days=${days}&limit=${limit}`,
      undefined,
      signal,
    ),
  testGaps: (path: string, limit = 50, signal?: AbortSignal) =>
    call<TestMap>(
      `/api/test_gaps?path=${encodeURIComponent(path)}&limit=${limit}`,
      undefined,
      signal,
    ),
  commands: (path: string, signal?: AbortSignal) =>
    call<WorkspaceCommands>(
      `/api/commands?path=${encodeURIComponent(path)}`,
      undefined,
      signal,
    ),
  surface: (path: string, signal?: AbortSignal) =>
    call<SurfaceReport>(
      `/api/surface?path=${encodeURIComponent(path)}`,
      undefined,
      signal,
    ),

  // ── Fleet ─────────────────────────────────────────────────────────────
  fleetList: () => call<FleetListResponse>('/api/fleet'),
  fleetFind: (pattern: string, opts: { kind?: string; limit?: number } = {}) => {
    const parts = [`pattern=${encodeURIComponent(pattern)}`];
    if (opts.kind) parts.push(`kind=${encodeURIComponent(opts.kind)}`);
    if (opts.limit != null) parts.push(`limit=${opts.limit}`);
    return call<FleetFindResponse>(`/api/fleet/find?${parts.join('&')}`);
  },
  fleetHotspots: (limit = 25) =>
    call<FleetHotspotsResponse>(`/api/fleet/hotspots?limit=${limit}`),
  fleetTestGaps: (limit = 25) =>
    call<FleetTestGapsResponse>(`/api/fleet/test_gaps?limit=${limit}`),
  fleetDiff: (from: string, to: string) =>
    call<FleetDiffResponse>(
      `/api/fleet/surface_diff?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`,
    ),

  // ── Hybrid semantic + BM25 search ─────────────────────────────────────
  searchCode: (
    path: string,
    q: string,
    opts: { limit?: number; lang?: string; kind?: string } = {},
  ) => {
    const parts = [`path=${encodeURIComponent(path)}`, `q=${encodeURIComponent(q)}`];
    if (opts.limit != null) parts.push(`limit=${opts.limit}`);
    if (opts.lang) parts.push(`lang=${encodeURIComponent(opts.lang)}`);
    if (opts.kind) parts.push(`kind=${encodeURIComponent(opts.kind)}`);
    return call<SearchResponse>(`/api/search?${parts.join('&')}`);
  },
  searchStatus: (path: string, signal?: AbortSignal) =>
    call<IndexStatus>(
      `/api/search/status?path=${encodeURIComponent(path)}`,
      undefined,
      signal,
    ),
  searchReindex: (path: string, opts: { full?: boolean; bm25Only?: boolean } = {}) => {
    const parts = [`path=${encodeURIComponent(path)}`];
    if (opts.full) parts.push('full=true');
    if (opts.bm25Only) parts.push('bm25_only=true');
    return call<IndexStatus>(`/api/search/reindex?${parts.join('&')}`, { method: 'POST' });
  },

  // ── Transitive xref ────────────────────────────────────────────────────
  impact: (path: string, sym: string, depth = 3, signal?: AbortSignal) =>
    call<ImpactReport>(
      `/api/impact?path=${encodeURIComponent(path)}&sym=${encodeURIComponent(sym)}&depth=${depth}`,
      undefined,
      signal,
    ),
  flow: (path: string, sym: string, depth = 3, signal?: AbortSignal) =>
    call<FlowReport>(
      `/api/flow?path=${encodeURIComponent(path)}&sym=${encodeURIComponent(sym)}&depth=${depth}`,
      undefined,
      signal,
    ),
  symbol360: (path: string, sym: string, signal?: AbortSignal) =>
    call<Symbol360>(
      `/api/symbol?path=${encodeURIComponent(path)}&sym=${encodeURIComponent(sym)}`,
      undefined,
      signal,
    ),

  // ── Context artifacts ─────────────────────────────────────────────────
  contextList: (path: string, signal?: AbortSignal) =>
    call<ContextListResponse>(
      `/api/context?path=${encodeURIComponent(path)}`,
      undefined,
      signal,
    ),
  contextGet: (path: string, name: string, signal?: AbortSignal) =>
    call<ContextArtifactContent>(
      `/api/context/get?path=${encodeURIComponent(path)}&name=${encodeURIComponent(name)}`,
      undefined,
      signal,
    ),
  contextSearch: (path: string, q: string, limit = 10) =>
    call<SearchResponse>(
      `/api/context/search?path=${encodeURIComponent(path)}&q=${encodeURIComponent(q)}&limit=${limit}`,
    ),
  contextIndex: (path: string) =>
    call<{ indexed_chunks: number }>(`/api/context/index?path=${encodeURIComponent(path)}`, {
      method: 'POST',
    }),
};
